# File: rhel9-baseline.yml (Enhanced)
---
- name: Post-SCAP Configuration and Validation for RHEL 9 Template
  become: true
  become_method: sudo
  gather_facts: true
  hosts: all
  
  # [STIG-ID V-257777] Pre-tasks to validate SCAP application
  pre_tasks:
    - name: Verify SCAP profile was applied during kickstart
      stat:
        path: /root/ks-post.log
      register: ks_log
      
    - name: Display kickstart post-installation log
      command: tail -50 /root/ks-post.log
      when: ks_log.stat.exists
      changed_when: false
      
    - name: Verify FIPS mode is enabled
      command: cat /proc/sys/crypto/fips_enabled
      register: fips_status
      changed_when: false
      failed_when: fips_status.stdout != "1"
      
    - name: Verify SELinux is enforcing
      command: getenforce
      register: selinux_status
      changed_when: false
      failed_when: selinux_status.stdout != "Enforcing"
      
    - name: Verify AIDE database exists
      stat:
        path: /var/lib/aide/aide.db.gz
      register: aide_db
      failed_when: not aide_db.stat.exists

  roles:
    # [STIG-ID V-257959] Configure DNS client
    - role: dns_client
      dns_server_1: 192.168.51.65
      dns_server_2: 192.168.51.65   # Role isn't smart enough to only include those that are here
      search_domain: kten.test

    # [STIG-ID V-257780] System base configuration
    - role: system_base
      connected_network: false    # Required to ensure nothing tries to access the Internet
      ca_pem_path: https://garden.kten.test/certs/ceist-ca.crt
      preconfigure_cloud_init: true

    # [STIG-ID V-257842] Configure service accounts
    - role: system_users

    # [STIG-ID V-257780] System-specific configuration
    - role: system_configure
      connected_network: false    # Required to ensure nothing tries to access the Internet
      configure_local_cert_authority: true
      ca_pem_path: https://garden.kten.test/certs/ceist-ca.crt

    # [STIG-ID V-257780] Final cleanup and preparation
    - role: system_clean
      connected_network: false    # Required to ensure nothing tries to access the Internet
      preconfigure_cloud_init: true

  # [STIG-ID V-257849] Post-tasks for compliance validation
  post_tasks:
    - name: Run OpenSCAP compliance validation scan
      block:
        - name: Execute OpenSCAP STIG compliance scan
          command: >
            oscap xccdf eval
            --profile xccdf_org.ssgproject.content_profile_stig
            --results /root/oscap-post-ansible-results.xml
            --report /root/oscap-post-ansible-report.html
            /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
          register: oscap_result
          failed_when: false
          changed_when: false
          
        - name: Fetch SCAP results to local machine
          fetch:
            src: /root/oscap-post-ansible-results.xml
            dest: "./scap-results/{{ inventory_hostname }}-results.xml"
            flat: yes
            
        - name: Fetch SCAP report to local machine
          fetch:
            src: /root/oscap-post-ansible-report.html
            dest: "./scap-results/{{ inventory_hostname }}-report.html"
            flat: yes
            
        - name: Display SCAP scan summary
          debug:
            msg: |
              SCAP Compliance Scan Complete
              Results: ./scap-results/{{ inventory_hostname }}-results.xml
              Report: ./scap-results/{{ inventory_hostname }}-report.html
              Exit Code: {{ oscap_result.rc }}
              
    - name: Generate compliance summary
      block:
        - name: Create compliance summary
          copy:
            dest: /root/compliance-summary.txt
            content: |
              ========================================
              RHEL 9 STIG Compliance Summary
              ========================================
              Hostname: {{ ansible_hostname }}
              Build Date: {{ ansible_date_time.iso8601 }}
              SCAP Profile: DISA STIG for RHEL 9
              
              Security Controls Applied:
              - FIPS 140-3 Mode: {{ fips_status.stdout }}
              - SELinux: {{ selinux_status.stdout }}
              - AIDE Database: {{ 'Initialized' if aide_db.stat.exists else 'Not Found' }}
              - Audit Logging: Enabled
              - USBGuard: Configured
              
              Post-Ansible SCAP Scan: {{ oscap_result.rc }}
              ========================================
            mode: '0600'
            
        - name: Display compliance summary
          command: cat /root/compliance-summary.txt
          changed_when: false
          
    - name: Verify critical STIG controls
      block:
        - name: Check fapolicyd status
          systemd:
            name: fapolicyd
          register: fapolicyd_status
          
        - name: Check auditd status
          systemd:
            name: auditd
          register: auditd_status
          
        - name: Check firewalld status
          systemd:
            name: firewalld
          register: firewalld_status
          
        - name: Display service status
          debug:
            msg: |
              Critical Services Status:
              - fapolicyd: {{ fapolicyd_status.status.ActiveState }}
              - auditd: {{ auditd_status.status.ActiveState }}
              - firewalld: {{ firewalld_status.status.ActiveState }}
