#!/bin/sh
# File: build.sh
# Copyright 2022-2025 Korea Battle Simulation Center. All rights reserved.
# SPDX-License-Identifier: MIT
#
# GitLab Runner Configuration for QEMU/KVM Packer Builds
# Compliance: [DISA STIG RHEL 9, NIST SP 800-53 Rev 5]
# Target: garden.kten.mil GitLab Runner
# Purpose: Enable QEMU builder execution for KVM image generation
# Last Updated: 2024
# Generated by: AskSage (https://chat.genai.army.mil/)
#

#
# REQUIRED CHANGES TO GITLAB RUNNER HOST (garden.kten.mil)
#

# ============================================================================
# 1. INSTALL QEMU/KVM PACKAGES
# ============================================================================
# [STIG-ID V-257779] [NIST SC-13] Hardware virtualization support

# Install QEMU, KVM, and required dependencies
sudo dnf install -y \
  qemu-kvm \
  qemu-img \
  qemu-system-x86 \
  libvirt \
  libvirt-daemon-kvm \
  virt-install \
  bridge-utils \
  edk2-ovmf

# Verify KVM kernel module is loaded
lsmod | grep kvm
# Expected output: kvm_intel or kvm_amd

# If not loaded, load the module
sudo modprobe kvm
sudo modprobe kvm_intel  # or kvm_amd for AMD processors

# Enable KVM module on boot
echo "kvm" | sudo tee -a /etc/modules-load.d/kvm.conf
echo "kvm_intel" | sudo tee -a /etc/modules-load.d/kvm.conf  # or kvm_amd

# ============================================================================
# 2. CONFIGURE GITLAB RUNNER USER PERMISSIONS
# ============================================================================
# [STIG-ID V-257842] [NIST AC-6] Least privilege with necessary KVM access

# Add gitlab-runner user to kvm and libvirt groups
sudo usermod -aG kvm gitlab-runner
sudo usermod -aG libvirt gitlab-runner
sudo usermod -aG qemu gitlab-runner

# Verify group membership
id gitlab-runner
# Expected output should include: groups=...,kvm,libvirt,qemu

# ============================================================================
# 3. CONFIGURE KVM DEVICE PERMISSIONS
# ============================================================================
# [STIG-ID V-257779] [NIST AC-3] Access enforcement for KVM devices

# Set proper permissions on /dev/kvm
sudo chmod 660 /dev/kvm
sudo chown root:kvm /dev/kvm

# Create udev rule for persistent permissions
cat <<'EOF' | sudo tee /etc/udev/rules.d/65-kvm.rules
# [STIG-ID V-257779] [NIST AC-3] KVM device access control
KERNEL=="kvm", GROUP="kvm", MODE="0660"
EOF

# Reload udev rules
sudo udevadm control --reload-rules
sudo udevadm trigger

# ============================================================================
# 4. CONFIGURE LIBVIRT FOR GITLAB RUNNER
# ============================================================================
# [STIG-ID V-257780] [NIST SC-7] Network isolation and access control

# Start and enable libvirtd service
sudo systemctl enable libvirtd
sudo systemctl start libvirtd

# Configure libvirt to allow gitlab-runner user access
# Edit /etc/libvirt/libvirtd.conf
sudo tee -a /etc/libvirt/libvirtd.conf > /dev/null <<'EOF'

# [STIG-ID V-257842] [NIST AC-6] GitLab Runner access configuration
unix_sock_group = "libvirt"
unix_sock_ro_perms = "0770"
unix_sock_rw_perms = "0770"
unix_sock_admin_perms = "0770"
auth_unix_ro = "none"
auth_unix_rw = "none"
EOF

# Restart libvirtd to apply changes
sudo systemctl restart libvirtd

# ============================================================================
# 5. CREATE REQUIRED DIRECTORIES WITH PROPER PERMISSIONS
# ============================================================================
# [STIG-ID V-257844] [NIST CM-2] Baseline configuration storage

# Create directory structure for Packer operations
sudo mkdir -p /var/lib/packer/{isos,output,cache}
sudo mkdir -p /opt/terraform/providers

# Set ownership to gitlab-runner
sudo chown -R gitlab-runner:gitlab-runner /var/lib/packer

# Set secure permissions
# [STIG-ID V-257790] [NIST SI-7] Protect build artifacts
sudo chmod 750 /var/lib/packer
sudo chmod 750 /var/lib/packer/isos
sudo chmod 750 /var/lib/packer/output
sudo chmod 750 /var/lib/packer/cache

# ============================================================================
# 6. CONFIGURE SELINUX CONTEXTS (RHEL 9)
# ============================================================================
# [STIG-ID V-257777] [NIST AC-3] SELinux mandatory access controls

# Set SELinux contexts for Packer directories
sudo semanage fcontext -a -t virt_image_t "/var/lib/packer/output(/.*)?"
sudo semanage fcontext -a -t virt_content_t "/var/lib/packer/isos(/.*)?"
sudo restorecon -Rv /var/lib/packer

# Allow gitlab-runner to use KVM
sudo setsebool -P virt_use_nfs 1
sudo setsebool -P virt_use_samba 1

# Create custom SELinux policy for gitlab-runner KVM access
cat <<'EOF' | sudo tee /tmp/gitlab_runner_kvm.te
module gitlab_runner_kvm 1.0;

require {
    type unconfined_service_t;
    type svirt_t;
    type virt_image_t;
    class process { execmem };
}

# Allow gitlab-runner to execute QEMU with KVM
allow unconfined_service_t self:process execmem;
allow unconfined_service_t virt_image_t:file { read write };
EOF

# Compile and install SELinux policy
sudo checkmodule -M -m -o /tmp/gitlab_runner_kvm.mod /tmp/gitlab_runner_kvm.te
sudo semodule_package -o /tmp/gitlab_runner_kvm.pp -m /tmp/gitlab_runner_kvm.mod
sudo semodule -i /tmp/gitlab_runner_kvm.pp

# ============================================================================
# 7. CONFIGURE NETWORK BRIDGE (OPTIONAL - FOR BRIDGED NETWORKING)
# ============================================================================
# [STIG-ID V-257780] [NIST SC-7] Network segmentation

# If you need bridged networking instead of user-mode networking:
# Create a bridge interface (example: br0)

# Note: For maximum security in closed networks, skip this section
# and use user-mode networking (default in the QEMU builder)

# Example bridge configuration (only if required):
# sudo nmcli connection add type bridge ifname br0 con-name br0
# sudo nmcli connection add type ethernet ifname ens192 master br0
# sudo nmcli connection up br0

# Configure libvirt network for bridge
# cat <<'EOF' | sudo tee /tmp/br0-network.xml
# <network>
#   <name>br0</name>
#   <forward mode="bridge"/>
#   <bridge name="br0"/>
# </network>
# EOF
# 
# sudo virsh net-define /tmp/br0-network.xml
# sudo virsh net-start br0
# sudo virsh net-autostart br0

# ============================================================================
# 8. CONFIGURE GITLAB RUNNER CONFIG.TOML
# ============================================================================
# [STIG-ID V-257842] [NIST SC-7] Secure runner configuration

# Edit GitLab Runner configuration: /etc/gitlab-runner/config.toml
# Add or modify the runner configuration for QEMU builds

sudo tee -a /etc/gitlab-runner/config.toml > /dev/null <<'EOF'

# [STIG-ID V-257842] [NIST CM-6] GitLab Runner for QEMU/KVM builds
[[runners]]
  name = "garden-kten-mil-qemu-runner"
  url = "https://gitlab.kten.mil/"
  token = "YOUR_RUNNER_TOKEN"  # Replace with actual token
  executor = "shell"
  
  # [STIG-ID V-257777] [NIST AC-3] Build isolation
  builds_dir = "/var/lib/packer/builds"
  cache_dir = "/var/lib/packer/cache"
  
  [runners.custom_build_dir]
    enabled = true
  
  [runners.cache]
    Type = "local"
    Shared = false
    [runners.cache.local]
      ServerAddress = ""
      
  # Environment variables for QEMU/KVM builds
  environment = [
    "PACKER_CACHE_DIR=/var/lib/packer/cache",
    "PACKER_LOG=1",
    "PACKER_LOG_PATH=/var/lib/packer/packer.log",
    "LIBVIRT_DEFAULT_URI=qemu:///system",
    "QEMU_AUDIO_DRV=none"
  ]
  
  # [STIG-ID V-257843] [NIST SC-24] Resource limits
  [runners.machine]
    MaxBuilds = 1
    IdleCount = 0
    IdleTime = 600
EOF

# Restart GitLab Runner to apply configuration
sudo systemctl restart gitlab-runner

# ============================================================================
# 9. VERIFY KVM ACCELERATION AVAILABILITY
# ============================================================================
# [STIG-ID V-257779] [NIST SC-13] Hardware security features

# Check if KVM acceleration is available
sudo -u gitlab-runner qemu-system-x86_64 -accel help
# Expected output should include: kvm

# Verify nested virtualization (if running on VM)
cat /sys/module/kvm_intel/parameters/nested  # Should show 'Y' or '1'
# or for AMD:
cat /sys/module/kvm_amd/parameters/nested

# If nested virtualization is disabled, enable it:
# For Intel:
# echo "options kvm_intel nested=1" | sudo tee /etc/modprobe.d/kvm.conf
# For AMD:
# echo "options kvm_amd nested=1" | sudo tee /etc/modprobe.d/kvm.conf
# Then reboot or reload the module

# ============================================================================
# 10. CONFIGURE FIREWALL (IF APPLICABLE)
# ============================================================================
# [STIG-ID V-257780] [NIST SC-7] Boundary protection

# If using VNC for debugging (should be localhost-only per builder config)
# No firewall changes needed as VNC binds to 127.0.0.1

# If using HTTP server for kickstart delivery in closed network:
sudo firewall-cmd --permanent --add-port=8000-8100/tcp
sudo firewall-cmd --reload

# ============================================================================
# 11. INSTALL PACKER (IF NOT ALREADY INSTALLED)
# ============================================================================
# [STIG-ID V-257790] [NIST SI-7] Software integrity verification

# Download Packer from internal mirror or transfer manually
# For closed network, download on a connected system and transfer

# Example: Download Packer 1.10.0 (adjust version as needed)
PACKER_VERSION="1.10.0"
cd /tmp

# On connected system:
# wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
# wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS
# wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS.sig

# Transfer to garden.kten.mil and verify checksum
# sha256sum -c packer_${PACKER_VERSION}_SHA256SUMS 2>&1 | grep OK

# Install Packer
sudo unzip packer_${PACKER_VERSION}_linux_amd64.zip -d /usr/local/bin/
sudo chmod +x /usr/local/bin/packer

# Verify installation
packer version

# Install QEMU plugin for Packer
sudo -u gitlab-runner packer plugins install github.com/hashicorp/qemu

# ============================================================================
# 12. CONFIGURE AUDIT LOGGING
# ============================================================================
# [STIG-ID V-257777] [NIST AU-2] Audit events

# Add audit rules for QEMU/KVM operations
cat <<'EOF' | sudo tee -a /etc/audit/rules.d/qemu-kvm.rules
# [STIG-ID V-257777] [NIST AU-2] Audit QEMU/KVM operations
-w /usr/bin/qemu-system-x86_64 -p x -k qemu_execution
-w /dev/kvm -p rw -k kvm_access
-w /var/lib/packer/ -p wa -k packer_artifacts
-w /var/lib/libvirt/ -p wa -k libvirt_operations
EOF

# Reload audit rules
sudo augenrules --load

# ============================================================================
# 13. CONFIGURE RESOURCE LIMITS
# ============================================================================
# [STIG-ID V-257843] [NIST SC-24] Resource allocation

# Set resource limits for gitlab-runner user
cat <<'EOF' | sudo tee /etc/security/limits.d/gitlab-runner.conf
# [STIG-ID V-257843] [NIST SC-24] GitLab Runner resource limits
gitlab-runner soft nofile 65536
gitlab-runner hard nofile 65536
gitlab-runner soft nproc 4096
gitlab-runner hard nproc 4096
gitlab-runner soft memlock unlimited
gitlab-runner hard memlock unlimited
EOF

# ============================================================================
# 14. VERIFICATION STEPS
# ============================================================================

# Test 1: Verify gitlab-runner can access KVM
echo "Test 1: KVM Access"
sudo -u gitlab-runner test -r /dev/kvm && echo "✓ KVM readable" || echo "✗ KVM not readable"
sudo -u gitlab-runner test -w /dev/kvm && echo "✓ KVM writable" || echo "✗ KVM not writable"

# Test 2: Verify QEMU can use KVM acceleration
echo "Test 2: QEMU KVM Acceleration"
sudo -u gitlab-runner qemu-system-x86_64 -accel kvm -m 512 -nographic -serial none -monitor none -display none &
QEMU_PID=$!
sleep 2
if ps -p $QEMU_PID > /dev/null; then
    echo "✓ QEMU with KVM acceleration works"
    sudo kill $QEMU_PID
else
    echo "✗ QEMU with KVM acceleration failed"
fi

# Test 3: Verify directory permissions
echo "Test 3: Directory Permissions"
sudo -u gitlab-runner test -w /var/lib/packer/output && echo "✓ Output directory writable" || echo "✗ Output directory not writable"
sudo -u gitlab-runner test -r /var/lib/packer/isos && echo "✓ ISO directory readable" || echo "✗ ISO directory not readable"

# Test 4: Verify libvirt access
echo "Test 4: Libvirt Access"
sudo -u gitlab-runner virsh version && echo "✓ Libvirt accessible" || echo "✗ Libvirt not accessible"

# Test 5: Verify Packer installation
echo "Test 5: Packer Installation"
sudo -u gitlab-runner packer version && echo "✓ Packer installed" || echo "✗ Packer not installed"

# Test 6: Verify SELinux contexts
echo "Test 6: SELinux Contexts"
ls -Z /var/lib/packer/output | grep virt_image_t && echo "✓ SELinux contexts correct" || echo "✗ SELinux contexts incorrect"

# ============================================================================
# 15. GITLAB CI/CD PIPELINE CONFIGURATION
# ============================================================================

# Create .gitlab-ci.yml in your repository with QEMU build job
cat <<'EOF' > .gitlab-ci.yml.example
# [STIG-ID V-257777] [NIST CM-6] Automated secure image builds
# GitLab CI/CD Pipeline for QEMU/KVM Packer Builds

variables:
  PACKER_CACHE_DIR: "/var/lib/packer/cache"
  PACKER_LOG: "1"
  PACKER_LOG_PATH: "/var/lib/packer/packer-${CI_PIPELINE_ID}.log"
  ISO_CHECKSUM: "sha256:YOUR_RHEL9_ISO_CHECKSUM"
  ISO_URL: "file:///var/lib/packer/isos/rhel-9.3-x86_64-dvd.iso"

stages:
  - validate
  - build
  - verify

# [STIG-ID V-257790] [NIST SI-7] Validate configuration before build
validate:packer:
  stage: validate
  tags:
    - qemu
    - kvm
  script:
    - packer init .
    - packer fmt -check .
    - packer validate -var "iso_url_local=${ISO_URL}" -var "iso_checksum=${ISO_CHECKSUM}" .
  only:
    - merge_requests
    - main

# [STIG-ID V-257777] [NIST CM-2] Build hardened KVM image
build:rhel9-minimal:
  stage: build
  tags:
    - qemu
    - kvm
  script:
    - packer init .
    - |
      packer build \
        -var "iso_url_local=${ISO_URL}" \
        -var "iso_checksum=${ISO_CHECKSUM}" \
        -var "qemu_output_directory=/var/lib/packer/output" \
        -var "vm_name_prefix=rhel9-minimal-${CI_PIPELINE_ID}" \
        -on-error=abort \
        .
  artifacts:
    paths:
      - /var/lib/packer/output/rhel9-minimal-*/
    expire_in: 7 days
  only:
    - main
  timeout: 2h

# [STIG-ID V-257844] [NIST CM-2] Verify built image
verify:image:
  stage: verify
  tags:
    - qemu
    - kvm
  script:
    - |
      IMAGE_PATH=$(find /var/lib/packer/output -name "*.qcow2" -type f | head -n 1)
      echo "Verifying image: ${IMAGE_PATH}"
      
      # Verify image integrity
      qemu-img check "${IMAGE_PATH}"
      
      # Display image info
      qemu-img info "${IMAGE_PATH}"
      
      # Verify image size is reasonable (not corrupted)
      IMAGE_SIZE=$(qemu-img info --output=json "${IMAGE_PATH}" | jq -r '.["virtual-size"]')
      if [ "${IMAGE_SIZE}" -lt 1073741824 ]; then
        echo "Error: Image size too small, possible corruption"
        exit 1
      fi
      
      echo "✓ Image verification successful"
  dependencies:
    - build:rhel9-minimal
  only:
    - main
EOF

# ============================================================================
# 16. SECURITY HARDENING CHECKLIST
# ============================================================================

cat <<'EOF' > /tmp/qemu-runner-security-checklist.txt
# [STIG-ID V-257777] [NIST SC-13] QEMU/KVM Runner Security Checklist

□ KVM kernel module loaded and enabled on boot
□ gitlab-runner user added to kvm, libvirt, and qemu groups
□ /dev/kvm permissions set to 660 with kvm group ownership
□ udev rules configured for persistent KVM device permissions
□ libvirtd service enabled and running
□ libvirt configured for gitlab-runner access
□ Packer directories created with proper ownership and permissions
□ SELinux contexts configured for Packer directories
□ SELinux policy module installed for gitlab-runner KVM access
□ GitLab Runner config.toml updated with QEMU runner configuration
□ KVM acceleration verified and functional
□ Firewall configured (if HTTP server needed for kickstart)
□ Packer installed and QEMU plugin available
□ Audit rules configured for QEMU/KVM operations
□ Resource limits configured for gitlab-runner user
□ All verification tests passed
□ GitLab CI/CD pipeline configured with QEMU tags
□ ISO files staged in /var/lib/packer/isos/
□ SSH private key for Packer available to gitlab-runner
□ Network bridge configured (if required, otherwise use user-mode)
□ OVMF firmware files available for UEFI boot

# Additional Security Considerations
□ Ensure gitlab-runner user cannot escalate privileges
□ Verify no unnecessary services running on runner host
□ Confirm audit logs are being collected and monitored
□ Validate SELinux is in enforcing mode
□ Ensure FIPS mode enabled if required
□ Verify runner host is patched and up-to-date
□ Confirm runner host has sufficient disk space for builds
□ Validate network isolation for closed network compliance
EOF

cat /tmp/qemu-runner-security-checklist.txt

# ============================================================================
# 17. TROUBLESHOOTING COMMANDS
# ============================================================================

cat <<'EOF' > /tmp/qemu-runner-troubleshooting.sh
#!/bin/bash
# [STIG-ID V-257777] QEMU/KVM Runner Troubleshooting Script

echo "=== GitLab Runner QEMU/KVM Troubleshooting ==="

echo -e "\n1. KVM Module Status:"
lsmod | grep kvm

echo -e "\n2. KVM Device Permissions:"
ls -l /dev/kvm

echo -e "\n3. GitLab Runner User Groups:"
id gitlab-runner

echo -e "\n4. Libvirt Status:"
systemctl status libvirtd --no-pager

echo -e "\n5. Packer Version:"
sudo -u gitlab-runner packer version

echo -e "\n6. QEMU Version:"
qemu-system-x86_64 --version

echo -e "\n7. KVM Acceleration Test:"
sudo -u gitlab-runner qemu-system-x86_64 -accel help

echo -e "\n8. Directory Permissions:"
ls -ld /var/lib/packer/*

echo -e "\n9. SELinux Status:"
getenforce
ls -Z /var/lib/packer/

echo -e "\n10. Recent Audit Logs for QEMU:"
sudo ausearch -k qemu_execution -ts recent 2>/dev/null | tail -20

echo -e "\n11. GitLab Runner Status:"
systemctl status gitlab-runner --no-pager

echo -e "\n12. Available Disk Space:"
df -h /var/lib/packer

echo -e "\n13. Memory Available:"
free -h

echo -e "\n14. CPU Info (Virtualization Support):"
grep -E 'vmx|svm' /proc/cpuinfo | head -1

echo -e "\n=== End Troubleshooting ==="
EOF

chmod +x /tmp/qemu-runner-troubleshooting.sh

# ============================================================================
# REFERENCES
# ============================================================================
# [1] DISA STIG for Red Hat Enterprise Linux 9
#     https://public.cyber.mil/stigs/downloads/
# [2] NIST SP 800-53 Rev 5 Security and Privacy Controls
#     https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final
# [3] GitLab Runner Documentation
#     https://docs.gitlab.com/runner/
# [4] QEMU/KVM Documentation
#     https://www.qemu.org/documentation/
# [5] Packer QEMU Builder Documentation
#     https://developer.hashicorp.com/packer/integrations/hashicorp/qemu
# [6] Red Hat Virtualization Deployment and Administration Guide
#     https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_and_managing_virtualization/
# [7] SELinux User's and Administrator's Guide
#     https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/using_selinux/